eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8085/eureka
  instance:
    leaseRenewalIntervalInSeconds: 5

serviceDicovery:
  orderService: ORDER-SERVICE
spring:
  application:
    name: Customer-Service
  data:
    mongodb:
      database: customer_db
      host: localhost
      port: 27017
      repositories:
        enabled: true

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

  cache:
    type: redis

  redis:
    host: localhost
    port: 6379
    expiration: 500

  cloud:
      stream:
        bindings:
          customerChannel:
            destination: exchange
        default:
          contentType: application/json
        rabbit:
          bindings:
            customerChannel:
              producer:
                routingKeyExpression: '"customer-queue"'